from __future__ import annotations

import os
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(PROJECT_ROOT / "exports" / ".mpl_cache"))
os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np
import pandas as pd


def get_project_root() -> Path:
    return PROJECT_ROOT


def _format_currency(value: float) -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "$0.00"
    return f"${value:,.2f}"


def _format_int(value: float) -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return "0"
    return f"{int(round(value)):,}"


def _safe_get(df: pd.DataFrame, promo_day: str, col: str) -> float:
    if df.empty or col not in df.columns:
        return 0.0
    row = df[df["promo_day_type"] == promo_day]
    if row.empty:
        return 0.0
    return float(row.iloc[0][col])


def load_exports(project_root: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    exports_dir = project_root / "exports"
    summary_by_day = pd.read_csv(exports_dir / "hh_summary_by_promo_day.csv")
    fruit_tea_summary = pd.read_csv(exports_dir / "fruit_tea_summary_by_promo_day.csv")
    product_lift = pd.read_csv(exports_dir / "fruit_tea_product_lift_by_promo_day.csv")
    return summary_by_day, fruit_tea_summary, product_lift


def set_plot_style() -> None:
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.edgecolor": "#222222",
            "axes.labelcolor": "#222222",
            "xtick.color": "#222222",
            "ytick.color": "#222222",
            "text.color": "#222222",
            "font.size": 12,
            "axes.titlesize": 18,
            "axes.titleweight": "bold",
            "font.sans-serif": [
                "PingFang SC",
                "Arial Unicode MS",
                "Noto Sans CJK SC",
                "DejaVu Sans",
            ],
        }
    )


def add_title_slide(pdf: PdfPages, title: str, subtitle: str) -> None:
    fig = plt.figure(figsize=(11, 8.5))
    fig.text(0.08, 0.7, title, fontsize=34, weight="bold")
    fig.text(0.08, 0.6, subtitle, fontsize=16, color="#555555")
    fig.text(0.08, 0.1, "Generated by Mosa Tea HH Analysis", fontsize=10, color="#777777")
    pdf.savefig(fig)
    plt.close(fig)


def add_summary_slide(pdf: PdfPages, summary: pd.DataFrame) -> None:
    fig = plt.figure(figsize=(11, 8.5))
    fig.text(0.08, 0.88, "Executive Summary", fontsize=24, weight="bold")

    monday_items = _safe_get(summary, "monday_flat_4", "total_items")
    monday_sales = _safe_get(summary, "monday_flat_4", "total_net_sales")
    weds_items = _safe_get(summary, "wednesday_bogo_50", "total_items")
    weds_sales = _safe_get(summary, "wednesday_bogo_50", "total_net_sales")

    table_data = [
        ["Monday Flat $4", _format_int(monday_items), _format_currency(monday_sales)],
        ["Wednesday BOGO 50%", _format_int(weds_items), _format_currency(weds_sales)],
    ]
    col_labels = ["Promo Day", "Total Items", "Total Net Sales"]

    ax = fig.add_axes([0.08, 0.52, 0.84, 0.3])
    ax.axis("off")
    table = ax.table(cellText=table_data, colLabels=col_labels, loc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(12)
    table.scale(1, 1.6)

    note = "Note: Verify net sales are populated; zeros indicate missing net_total data."
    fig.text(0.08, 0.18, note, fontsize=10, color="#777777")

    pdf.savefig(fig)
    plt.close(fig)


def add_hh_sales_slide(pdf: PdfPages, summary: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(11, 8.5))
    labels = (
        summary["promo_day_type"]
        .replace(
            {
                "monday_flat_4": "Monday: Flat $4 (Fruit Tea)",
                "wednesday_bogo_50": "Wednesday: BOGO 50% (Fruit Tea)",
            }
        )
        .tolist()
    )
    values = summary["total_net_sales"].tolist()
    title = "Happy Hour Net Sales by Promo Day"
    if "estimated_revenue" in summary.columns and sum(values) == 0:
        values = summary["estimated_revenue"].tolist()
        title = "Happy Hour Estimated Revenue (Qty x Price) by Promo Day"

    colors = ["#2A9D8F", "#E76F51"]
    ax.bar(labels, values, color=colors[: len(values)])
    ax.set_title(title)
    ax.set_xlabel("")
    ax.set_ylabel("Total Revenue")
    fig.subplots_adjust(bottom=0.18)
    fig.text(
        0.5,
        0.03,
        "Happy Hour window: Mon/Wed 2–5pm (PDT), 2025-10-20 to 2025-12-31",
        ha="center",
        va="bottom",
        fontsize=11,
        color="#555555",
    )
    ax.tick_params(axis="x", rotation=10, labelsize=10)
    ax.yaxis.set_major_formatter(StrMethodFormatter("${x:,.0f}"))

    for i, val in enumerate(values):
        ax.text(i, val, _format_currency(val), ha="center", va="bottom", fontsize=11)

    fig.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)

def add_hh_items_slide(pdf: PdfPages, summary: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(11, 8.5))
    labels = (
        summary["promo_day_type"]
        .replace(
            {
                "monday_flat_4": "Monday: Flat $4 (Fruit Tea)",
                "wednesday_bogo_50": "Wednesday: BOGO 50% (Fruit Tea)",
            }
        )
        .tolist()
    )
    values = summary["total_items"].tolist()

    colors = ["#457B9D", "#F4A261"]
    ax.bar(labels, values, color=colors[: len(values)])
    ax.set_title("Happy Hour Total Items by Promo Day")
    ax.set_xlabel("")
    ax.set_ylabel("Total Items")
    fig.subplots_adjust(bottom=0.18)
    fig.text(
        0.5,
        0.03,
        "Happy Hour window: Mon/Wed 2–5pm (PDT), 2025-10-20 to 2025-12-31",
        ha="center",
        va="bottom",
        fontsize=11,
        color="#555555",
    )
    ax.tick_params(axis="x", rotation=10, labelsize=10)
    ax.yaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))

    for i, val in enumerate(values):
        ax.text(i, val, _format_int(val), ha="center", va="bottom", fontsize=11)

    fig.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)


def add_fruit_tea_slide(pdf: PdfPages, fruit_tea_summary: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(11, 8.5))
    labels = (
        fruit_tea_summary["promo_day_type"]
        .replace(
            {
                "monday_flat_4": "Monday: Flat $4 (Fruit Tea)",
                "wednesday_bogo_50": "Wednesday: BOGO 50% (Fruit Tea)",
            }
        )
        .tolist()
    )
    values = fruit_tea_summary["fruit_tea_quantity"].tolist()

    ax.bar(labels, values, color="#264653")
    ax.set_title("Fruit Tea Quantity by Promo Day")
    ax.set_xlabel("")
    ax.set_ylabel("Fruit Tea Quantity")
    fig.subplots_adjust(bottom=0.18)
    fig.text(
        0.5,
        0.03,
        "Happy Hour window: Mon/Wed 2–5pm (PDT), 2025-10-20 to 2025-12-31",
        ha="center",
        va="bottom",
        fontsize=11,
        color="#555555",
    )
    ax.tick_params(axis="x", rotation=10, labelsize=10)
    ax.yaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))

    for i, val in enumerate(values):
        ax.text(i, val, _format_int(val), ha="center", va="bottom", fontsize=11)

    fig.tight_layout()
    pdf.savefig(fig)
    plt.close(fig)


def _top_items(df: pd.DataFrame, promo_day: str, top_n: int) -> pd.DataFrame:
    subset = df[df["promo_day_type"] == promo_day].copy()
    return subset.sort_values("total_quantity", ascending=False).head(top_n)


def add_top_items_slide(pdf: PdfPages, product_lift: pd.DataFrame) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(11, 8.5), sharex=False)
    fig.suptitle("Top Fruit Tea Items by Promo Day", fontsize=20, weight="bold")

    monday = _top_items(product_lift, "monday_flat_4", 8)
    weds = _top_items(product_lift, "wednesday_bogo_50", 8)

    axes[0].barh(monday["item_name"], monday["total_quantity"], color="#2A9D8F")
    axes[0].set_title("Monday Flat $4")
    axes[0].invert_yaxis()

    axes[1].barh(weds["item_name"], weds["total_quantity"], color="#E76F51")
    axes[1].set_title("Wednesday BOGO 50%")
    axes[1].invert_yaxis()

    for ax in axes:
        ax.set_xlabel("Total Quantity")
        ax.xaxis.set_major_formatter(StrMethodFormatter("{x:,.0f}"))

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    pdf.savefig(fig)
    plt.close(fig)


def add_takeaways_slide(pdf: PdfPages, summary: pd.DataFrame, fruit_tea_summary: pd.DataFrame) -> None:
    fig = plt.figure(figsize=(11, 8.5))
    fig.text(0.08, 0.88, "Key Takeaways", fontsize=24, weight="bold")

    monday_sales = _safe_get(summary, "monday_flat_4", "total_net_sales")
    weds_sales = _safe_get(summary, "wednesday_bogo_50", "total_net_sales")
    monday_ft_qty = _safe_get(fruit_tea_summary, "monday_flat_4", "fruit_tea_quantity")
    weds_ft_qty = _safe_get(fruit_tea_summary, "wednesday_bogo_50", "fruit_tea_quantity")

    winner_sales = "Monday" if monday_sales >= weds_sales else "Wednesday"
    winner_ft = "Monday" if monday_ft_qty >= weds_ft_qty else "Wednesday"

    bullets = [
        f"{winner_sales} shows higher net sales in the Happy Hour window.",
        f"{winner_ft} leads in Fruit Tea volume within Happy Hour.",
        "Top items are consistent across days; consider highlighting top 2 for menu callouts.",
        "If net sales are zero, re-run pipeline to ensure net_total is retained.",
    ]

    y = 0.72
    for bullet in bullets:
        fig.text(0.1, y, f"• {bullet}", fontsize=14)
        y -= 0.08

    pdf.savefig(fig)
    plt.close(fig)


def generate_presentation(pdf_path: Path) -> None:
    project_root = get_project_root()
    summary_by_day, fruit_tea_summary, product_lift = load_exports(project_root)

    set_plot_style()
    with PdfPages(pdf_path) as pdf:
        add_title_slide(
            pdf,
            "Mosa Tea Happy Hour Performance",
            "Monday Flat $4 vs Wednesday BOGO 50%",
        )
        add_summary_slide(pdf, summary_by_day)
        add_hh_sales_slide(pdf, summary_by_day)
        add_hh_items_slide(pdf, summary_by_day)
        add_fruit_tea_slide(pdf, fruit_tea_summary)
        add_top_items_slide(pdf, product_lift)
        add_takeaways_slide(pdf, summary_by_day, fruit_tea_summary)


def main() -> None:
    project_root = get_project_root()
    exports_dir = project_root / "exports"
    exports_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = exports_dir / "happy_hour_presentation.pdf"

    generate_presentation(pdf_path)
    print(f"Saved presentation PDF: {pdf_path}")


if __name__ == "__main__":
    main()
